#!/bin/bash

set -ex

mkdir $HOME/.jupyter
echo "c.NotebookApp.iopub_msg_rate_limit=1e22" >> $HOME/.jupyter/jupyter_notebook_config.py
echo "c.NotebookApp.iopub_data_rate_limit=1e22" >> $HOME/.jupyter/jupyter_notebook_config.py

jupyter nbextension enable --py --sys-prefix ipyturtle
